### ISSUE TITLE
Make workers profile aware or profiles worker aware

### ISSUE THREAD

**Issue by adityasaky** [kpcyrd/rebuilderd#126]
I'd like to be able to use some workers exclusively to rebuild selected profiles, for example, Arch Linux's `community` repository which has significantly more packages than `core` and `extra`. This would also allow for more granular control over which underlying host builds which packages. For example, heavier packages like `linux*`, `gcc` etc can be in a separate profile, that is always assigned to a host with the necessary resources.

**Comment by AKhozya** [comment]
Adding another use case for this feature.

I'm running rebuilderd on a homelab with 2 worker nodes contributing to Arch Linux reproducible builds. The challenge is resource allocation:

**The problem:**
- Most packages build fine with 6-9GB RAM
- A few monsters (electron, chromium, llvm, rust packages with LTO) need 12-16GB+
- Currently all workers get the same resources, so either:
  - Set high limits (12GB+) → wastes resources on small packages, fewer concurrent workers
  - Set lower limits (9GB) → ~3% of builds OOM and fail

**What would help:**
- Tag workers with capabilities (e.g., `memory=high`, `memory=low`)
- Tag packages or profiles with requirements
- Daemon routes heavy packages to capable workers

**Example config (wishlist):**
```toml
# Worker config
[worker]
name = "worker-small"
tags = ["memory=4G", "cpu=2"]

[worker]
name = "worker-large"  
tags = ["memory=16G", "cpu=8"]

# Package/profile routing
[routing]
packages = ["electron*", "chromium", "llvm*", "rust", "firefox"]
require_tags = ["memory=16G"]
```

This would allow efficient resource utilization while ensuring heavy builds get routed to capable workers.

Currently working around this by accepting ~3% OOM failure rate and letting packages retry, but proper routing would be much better.
